- name: Check if PiHole versions file exists
  ansible.builtin.stat:
    path: /etc/pihole/versions
  register: versions_file_stat

- name: Extract installed PiHole version
  ansible.builtin.command: "grep '^CORE_VERSION=' /etc/pihole/versions"
  register: core_version
  when: versions_file_stat.stat.exists
  changed_when: false

- name: Set facts for PiHole version
  ansible.builtin.set_fact:
    pihole_version_installed: "{{ core_version.stdout.split('=')[1][1:] }}"
  when: versions_file_stat.stat.exists

- name: Set default PiHole version
  ansible.builtin.set_fact:
    pihole_version_installed: "0.0.0"
  when: not versions_file_stat.stat.exists

- name: Display PiHole version
  ansible.builtin.debug:
    msg: "CORE_VERSION is {{ pihole_version_installed }}"
