- name: Install and configure PiHole
  when: pihole_version != pihole_version_installed
  block:
    - name: Download PiHole
      ansible.builtin.unarchive:
        src: https://github.com/pi-hole/pi-hole/archive/refs/tags/v{{ pihole_version }}.zip
        dest: /tmp
        remote_src: true
      changed_when: false

    - name: Install PiHole
      ansible.builtin.shell: |
        {% if ansible_os_family == 'RedHat' %}
        export PIHOLE_SKIP_OS_CHECK=true
        {% endif %}
        bash /tmp/pi-hole-{{ pihole_version }}/automated\ install/basic-install.sh --unattended
        rm -rf /tmp/*{{ pihole_version }}*
      register: process_status
      changed_when: false

    - name: Display installation process
      ansible.builtin.debug:
        var: process_status.stdout_lines
