---
- name: Install operating system checks dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ pihole_os_checks_dependencies }}"

- name: Install installer dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ pihole_installer_dependencies }}"

- name: Install Pi-hole dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ pihole_dependencies }}"

- name: Install updatelists dependencies
  when: pihole_updatelists_enable | bool
  ansible.builtin.package:
    name: "{{ pihole_updatelists_dependencies }}"
    state: present
