---
- name: Install installer dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - iproute
    - dialog
    - ca-certificates

- name: Install Pi-hole dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - cronie
    - curl
    - psmisc
    - sudo
    - unzip
    - libidn2
    - libcap
    - libcap
    - nmap-ncat
    - procps-ng
    - jq

- name: Install updatelists dependencies
  when: pihole_updatelists_enable | bool
  ansible.builtin.package:
    name:
      - php-cli
      - php-sqlite3
      - php-intl
      - php-curl
    state: present
