- name: Create PiHole setupVars.conf
  ansible.builtin.template:
    dest: /etc/pihole/setupVars.conf
    src: setupVars.conf.j2
    mode: "0644"

- name: Create PiHole pihole-FTL.conf
  ansible.builtin.template:
    dest: /etc/pihole/pihole-FTL.conf
    src: pihole-FTL.conf.j2
    mode: "0644"

- name: Create PiHole DNS custom.list
  ansible.builtin.template:
    dest: /etc/pihole/custom.list
    src: dns-custom-list.list.j2
    mode: "0644"
  when: pihole_local_dns_records is defined

- name: Create PiHole CNAME 05-pihole-custom-cname.conf
  ansible.builtin.template:
    dest: /etc/dnsmasq.d/05-pihole-custom-cname.conf
    src: cname-custom-list.conf.j2
    mode: "0644"
  when: pihole_local_cname_records is defined
